plugins { id 'java-library'; id 'java-test-fixtures' }
dependencies {
    api 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'io.projectreactor:reactor-core'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    compileOnly 'org.springframework:spring-webflux'
    testImplementation 'org.springframework:spring-webflux'
    testImplementation 'jakarta.servlet:jakarta.servlet-api'
    testFixturesImplementation 'com.nimbusds:nimbus-jose-jwt'
    testFixturesImplementation 'org.springframework:spring-core'
}

dependencyManagement { imports { mavenBom 'org.springframework.boot:spring-boot-dependencies:4.1.0' } }
