-- Privileged prerequisites for a fresh deployment, before central Flyway.
-- Configure LOGIN/passwords separately via the secret provisioner.
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='quant_migrator') THEN CREATE ROLE quant_migrator NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='quant_auth') THEN CREATE ROLE quant_auth NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='quant_portfolio') THEN CREATE ROLE quant_portfolio NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='quant_ingestion') THEN CREATE ROLE quant_ingestion NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='quant_scoring') THEN CREATE ROLE quant_scoring NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='quant_screener') THEN CREATE ROLE quant_screener NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='quant_search') THEN CREATE ROLE quant_search NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='quant_research') THEN CREATE ROLE quant_research NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF;
END $$;
SELECT format('GRANT CONNECT,CREATE ON DATABASE %I TO quant_migrator',current_database()) \gexec
GRANT USAGE,CREATE ON SCHEMA public TO quant_migrator;
ALTER SCHEMA public OWNER TO quant_migrator;
SELECT format('ALTER DATABASE %I OWNER TO quant_migrator',current_database()) \gexec
